version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'arieuqis'
      MYSQL_PASSWORD: 'deep'
      MYSQL_ROOT_PASSWORD: 'deep'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /my-db:/var/lib/mysql
volumes:
  my-db:
  

